/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blok;

import interfaces.ICenario;
import interfaces.IPlugin;
import interfaces.IPluginController;
import java.util.ArrayList;

/**
 *
 * @author flavi
 */
public class ModalSelectCenario extends javax.swing.JFrame {

    public ModalSelectCenario(IPluginController controller) {
        this.controller = controller;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboSelect = new javax.swing.JComboBox<Object>();
        btnComecarJogo = new javax.swing.JButton();
        lblMsgSelecione = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboSelect.setModel(new javax.swing.DefaultComboBoxModel<Object>(preencheCombo()));
        comboSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelectActionPerformed(evt);
            }
        });

        btnComecarJogo.setText("Começar Jogo");
        btnComecarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComecarJogoActionPerformed(evt);
            }
        });

        lblMsgSelecione.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMsgSelecione.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComecarJogo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboSelect, javax.swing.GroupLayout.Alignment.TRAILING, 0, 273, Short.MAX_VALUE)
                    .addComponent(lblMsgSelecione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblMsgSelecione, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnComecarJogo)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelectActionPerformed
        this.cenario = (ICenario) comboSelect.getSelectedItem();
    }//GEN-LAST:event_comboSelectActionPerformed

    private void btnComecarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComecarJogoActionPerformed
        if(!comboSelect.getSelectedItem().equals("Selecione"))
            this.iniciar();
        else
            lblMsgSelecione.setText("Favor selecionar um Plugin!");
    }//GEN-LAST:event_btnComecarJogoActionPerformed

    private Object [] preencheCombo(){
         
         ArrayList<Object> cenarios = new ArrayList<>();
         cenarios.add(new String("Selecione"));
         for (IPlugin plugin : ((PluginController)this.controller).getPluginsCarregados()) {
            if(plugin instanceof ICenario){
                cenarios.add(plugin);
            }
        }
        
        return cenarios.toArray();
    }
    
    private void iniciar(){
        MainWindow mainWindow = new MainWindow(cenario);
        mainWindow.setVisible(true);
        this.setVisible(false);
    }
    
    private ICenario cenario;
    private IPluginController controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComecarJogo;
    private javax.swing.JComboBox<Object> comboSelect;
    private javax.swing.JLabel lblMsgSelecione;
    // End of variables declaration//GEN-END:variables
}
