/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blok;

import interfaces.ICenario;
import interfaces.IJogador;
import interfaces.IPlugin;
import interfaces.IPluginController;
import java.util.ArrayList;

/**
 *
 * @author flavi
 */
public class ModalCombos extends javax.swing.JFrame {

    public ModalCombos(MainWindow mainWindow, IPluginController controller) {
        this.mainWindow = mainWindow;
        this.controller = controller;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboSelectCenario = new javax.swing.JComboBox<Object>();
        btnComecarJogo = new javax.swing.JButton();
        lblMsgSelecione = new javax.swing.JLabel();
        comboSelectJogador = new javax.swing.JComboBox<Object>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboSelectCenario.setModel(new javax.swing.DefaultComboBoxModel<Object>(preencheComboCenarios()));
        comboSelectCenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelectCenarioActionPerformed(evt);
            }
        });

        btnComecarJogo.setText("Começar Jogo");
        btnComecarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComecarJogoActionPerformed(evt);
            }
        });

        lblMsgSelecione.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMsgSelecione.setForeground(new java.awt.Color(204, 0, 51));

        comboSelectJogador.setModel(new javax.swing.DefaultComboBoxModel<Object>(preencheComboJogadores()));
        comboSelectJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelectJogadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnComecarJogo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMsgSelecione, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboSelectCenario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(comboSelectJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblMsgSelecione, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSelectCenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSelectJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnComecarJogo)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSelectCenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelectCenarioActionPerformed
        this.cenario = (ICenario) comboSelectCenario.getSelectedItem();
    }//GEN-LAST:event_comboSelectCenarioActionPerformed

    private void btnComecarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComecarJogoActionPerformed
        if((!comboSelectCenario.getSelectedItem().equals("Selecione")) &&
           (!comboSelectJogador.getSelectedItem().equals("Selecione")) )
            this.iniciar();
        
        if (comboSelectCenario.getSelectedItem().equals("Selecione"))
            lblMsgSelecione.setText("Favor selecionar um Plugin de Cenário!");
        
        if(comboSelectJogador.getSelectedItem().equals("Selecione"))
            lblMsgSelecione.setText("Favor selecionar um Plugin de Jogador!");
    }//GEN-LAST:event_btnComecarJogoActionPerformed

    private void comboSelectJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelectJogadorActionPerformed
        this.jogador = (IJogador) comboSelectJogador.getSelectedItem();
    }//GEN-LAST:event_comboSelectJogadorActionPerformed

    private Object [] preencheComboCenarios(){
         
         ArrayList<Object> cenarios = new ArrayList<>();
         cenarios.add(new String("Selecione"));
         for (IPlugin plugin : ((PluginController)this.controller).getPluginsCarregados()) {
            if(plugin instanceof ICenario){
                cenarios.add(plugin);
            }
        }
        
        return cenarios.toArray();
    }
    
    private Object [] preencheComboJogadores(){
         
         ArrayList<Object> jogadores = new ArrayList<>();
         jogadores.add(new String("Selecione"));
         for (IPlugin plugin : ((PluginController)this.controller).getPluginsCarregados()) {
            if(plugin instanceof IJogador){
                jogadores.add(plugin);
            }
        }
        
        return jogadores.toArray();
    }
    
    private void iniciar(){
        mainWindow.start(cenario, jogador);
        mainWindow.setVisible(true);
        this.setVisible(false);
    }

    private ICenario cenario;
    private IJogador jogador;
    private IPluginController controller;
    private MainWindow mainWindow;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComecarJogo;
    private javax.swing.JComboBox<Object> comboSelectCenario;
    private javax.swing.JComboBox<Object> comboSelectJogador;
    private javax.swing.JLabel lblMsgSelecione;
    // End of variables declaration//GEN-END:variables
}
